spring.application.name=challenge
# Habilita o console do H2 para acessar o banco pelo navegador
spring.h2.console.enabled=true
# Define o caminho para o console (você acessará em http://localhost:8080/h2-console)
spring.h2.console.path=/h2-console

# Configura a URL de conexão para um banco de dados em memória (in-memory) chamado 'kanchallengeDB'
spring.datasource.url=jdbc:h2:mem:kanchallengeDB    
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Configuração do JPA/Hibernate
# 'update' faz com que o Hibernate crie/atualize o schema do banco a partir das Entidades JPA
spring.jpa.hibernate.ddl-auto=update
# Exibe as instruções SQL geradas pelo Hibernate no console
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true